trigger:
  branches:
    include:
    - refs/heads/master
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: RunDockerCompose
  displayName: Run docker compose
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: DockerCompose@0
    displayName: Run a Docker Compose command
    inputs:
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: a7bcfb2d-65bd-4826-a6bc-df8c3d1b45c8
      dockerComposeFile: docker-compose.yml
      additionalDockerComposeFiles: docker-compose.override.yml
      dockerComposeFileArgs: >
        DOCKER_REGISTRY=modoranuc/
      dockerComposeCommand: push
    env:
      DOCKER_REGISTRY: 'modoranuc/'
    
...
