trigger:
  branches:
    include:
    - refs/heads/master
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: RunDockerCompose
  displayName: Run docker compose
  pool:
    name: WindowsLocal
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'k-market'
      dockerComposeFile: 'docker-compose.yml'
      additionalDockerComposeFiles: 'docker-compose.override.yml'
      dockerComposeFileArgs: 'DOCKER_REGISTRY=modoranuc/'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'push'
    
...
