trigger:
  branches:
    include:
    - refs/heads/master
parameters:
  - name: 'dockerfiles'
    type: object
    default:
      - [$(Build.SourcesDirectory)/src/Cart/Cart.API/Dockerfile, cartapi]
      - [$(Build.SourcesDirectory)/src/Customers/Customers.API/Dockerfile, customersapi]
      - [$(Build.SourcesDirectory)/src/Gateway/Gateway.API/Dockerfile, gatewayapi]
      - [$(Build.SourcesDirectory)/src/Order/Order.API/Dockerfile, orderapi]
      - [$(Build.SourcesDirectory)/src/Payments/Payments.API/Dockerfile, paymentsapi]
      - [$(Build.SourcesDirectory)/src/Products/Products.API/Dockerfile, productsapi]
      - [$(Build.SourcesDirectory)/src/Watchdog/Watchdog.WebApp/Dockerfile, watchdogwebapp]
      - [$(Build.SourcesDirectory)/src/Order/Order.SignalR/Dockerfile, ordersignalr]
  - name: 'registryName'
    type: string
    default: 'modoranuc'


name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: PushDockerImages
  displayName: Push images to docker hub
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - ${{ each dockerfile in parameters.dockerfiles }}:
    - task: Docker@2
      displayName: 'Build&push ${{ dockerfile[1] }}'
      inputs:
        containerRegistry: 'modoranuc'
        repository: '${{ parameters.registryName }}/${{ dockerfile[1] }}'
        command: 'buildAndPush'
        Dockerfile: '${{ dockerfile[0] }}'
        buildContext: '$(Build.SourcesDirectory)'



  
  
    
...
