version: '3.4'

services:
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: src/Gateway/Gateway.API/Dockerfile


  webstatus:
   image: ${DOCKER_REGISTRY-}webstatusapi
   build:
       context: .
       dockerfile: src/Watchdog/Watchdog.WebApp/Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: src/Cart/Cart.API/Dockerfile


  customers.api:
    image: ${DOCKER_REGISTRY-}customersapi
    build:
      context: .
      dockerfile: src/Customers/Customers.API/Dockerfile


  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: src/Products/Products.API/Dockerfile
  
  payments.api:
    image: ${DOCKER_REGISTRY-}paymentsapi
    build:
      context: .
      dockerfile: src/Payments/Payments.API/Dockerfile
  
  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: src/Order/Order.API/Dockerfile
  
  ordersignalr.api:
    image: ${DOCKER_REGISTRY-}ordersignalrapi
    build:
      context: .
      dockerfile: src/Order/Order.SignalR/Dockerfile

  messageBroker:
    image: rabbitmq:3.11.2-management