version: '3.4'

services:
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: src/Gateway/Gateway.API/Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: src/Cart/Cart.API/Dockerfile


  customers.api:
    image: ${DOCKER_REGISTRY-}customersapi
    build:
      context: .
      dockerfile: src/Customers/Customers.API/Dockerfile


  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: src/Products/Products.API/Dockerfile

