version: '3.4'

services:
  gateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Cart=http://cart.api
      - Services__Customers=http://customers.api
      - Services__Products=http://products.api
    ports:
      - "6001:80"
    depends_on:
      - cart.api
      - customers.api
      - products.api

  cart.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=host.docker.internal;User ID=sa;Password=aaaa1234;Database=Carts
    ports:
      - "6002:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  customers.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=host.docker.internal;User ID=sa;Password=aaaa1234;Database=Customers
    ports:
      - "6003:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Mongo__Host=mongodb://host.docker.internal:27017
    ports:
      - "6004:80"
