
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel1_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                Tip_proprietate = @"APT",
                Nr_camere = 3F,
                Suprafata = 65F,
                Suprafata_teren = 65F,
                An_constructie = 1985F,
                Zona = @"tudor-vladimirescu",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Pret with predicted Pret from sample data...\n\n");


            Console.WriteLine($"Tip_proprietate: {@"APT"}");
            Console.WriteLine($"Nr_camere: {3F}");
            Console.WriteLine($"Suprafata: {65F}");
            Console.WriteLine($"Suprafata_teren: {65F}");
            Console.WriteLine($"An_constructie: {1985F}");
            Console.WriteLine($"Zona: {@"tudor-vladimirescu"}");
            Console.WriteLine($"Pret: {314389F}");


            Console.WriteLine($"\n\nPredicted Pret: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
