﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Cart_API
{
    public partial class MLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"nr_camere", @"nr_camere"),new InputOutputColumnPair(@"suprafata", @"suprafata"),new InputOutputColumnPair(@"suprafata_teren", @"suprafata_teren"),new InputOutputColumnPair(@"an_constructie", @"an_constructie")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"tip_proprietate", @"tip_proprietate"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"zona", @"zona"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"nr_camere",@"suprafata",@"suprafata_teren",@"an_constructie",@"tip_proprietate",@"zona"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=20,NumberOfTrees=4,MaximumBinCountPerFeature=256,LearningRate=0.1F,FeatureFraction=1F,LabelColumnName=@"pret",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
