apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartapi
  template:
    metadata:
      labels:
        app: cartapi
    spec:
      containers:
      - name: cartapi
        image: modoranuc/cartapi
        imagePullPolicy: Always
        env:
      # - ConnectionStrings__SqlServer=Server=host.docker.internal;User ID=local;Password=aaaa1234;Database=Cart;TrustServerCertificate=true
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ConnectionStrings__SqlServer
            # value: Server=host.minikube.internal;User ID=local;Password=aaaa1234;Database=Cart;TrustServerCertificate=true
            valueFrom:
              configMapKeyRef:
                name: secrets-connection-strings
                key: SQL-CONNECTIONSTRING-CART
          # - name: EventQueue__Host
          - name: SERVICE-BUS-CONNECTIONSTRING
            valueFrom:
                configMapKeyRef:
                  name: secrets-connection-strings
                  key: SERVICE-BUS-CONNECTIONSTRING
            # value: host.minikube.internal
          # - name: EventQueue__Username
          #   value: guest
          # - name: EventQueue__Password
          #   value: guest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      
---
apiVersion: v1
kind: Service
metadata:
  name: cartsservice
spec:
  selector:
    app: cartapi
  ports:
  - port: 8080
    targetPort: 80

