apiVersion: apps/v1
kind: Deployment
metadata:
  name: customersapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customersapi
  template:
    metadata:
      labels:
        app: customersapi
    spec:
      containers:
      - name: customersapi
        image: modoranuc/customersapi
        imagePullPolicy: Always
        env:
          - name: ConnectionStrings__SqlServer
            value: Server=host.minikube.internal;User ID=local;Password=aaaa1234;Database=Customers;TrustServerCertificate=true
          - name: EventQueue__Host
            value: host.minikube.internal
          - name: EventQueue__Username
            value: guest
          - name: EventQueue__Password
            value: guest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      
---
apiVersion: v1
kind: Service
metadata:
  name: customersservice
spec:
  selector:
    app: customersapi
  ports:
  - port: 8080
    targetPort: 80

