apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayapi
  template:
    metadata:
      labels:
        app: gatewayapi
    spec:
      containers:
      - name: gatewayapi
        image: modoranuc/gatewayapi
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ConnectionStrings__SqlServer
            # value: Server=host.minikube.internal;User ID=local;Password=aaaa1234;Database=Auths;TrustServerCertificate=true
            valueFrom:
              configMapKeyRef:
                name: secrets-connection-strings
                key: SQL-CONNECTIONSTRING-AUTH
          - name: Services__Cart
            value: http://cartsservice:8080
          - name: Services__Customers
            value: http://customersservice:8080
          - name: Services__Products
            value: http://productsservice:8080
          - name: Services__Orders
            value: http://ordersservice:8080
          - name: Services__Payments
            value: http://paymentsservice:8080
          - name: GATEWAY_API_PATH_BASE
            value: "/backend"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayservice
spec:
  selector:
    app: gatewayapi
  ports:
  - port: 8080
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kenrmarketplaceapi
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1    
      nginx.ingress.kubernetes.io/use-regex: "true"
      # nginx.ingress.kubernetes.io/rewrite-target: /$3
spec:
  rules:
    - http:
        paths:
          - path: /(backend)(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: gatewayservice
                port:
                  number: 8080
          - path: /(metrics)(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: webstatusservice
                port:
                  number: 8080
