apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersignalr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersignalr
  template:
    metadata:
      labels:
        app: ordersignalr
    spec:
      containers:
      - name: ordersignalr
        image: modoranuc/ordersignalrapi
        imagePullPolicy: Always
        env:
          - name: EventQueue__Host
            value: host.minikube.internal
          - name: EventQueue__Username
            value: guest
          - name: EventQueue__Password
            value: guest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      
---
apiVersion: v1
kind: Service
metadata:
  name: ordersignalrservice
spec:
  selector:
    app: ordersignalr
  ports:
  - port: 8080
    targetPort: 80

