apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productsapi
  template:
    metadata:
      labels:
        app: productsapi
    spec:
      containers:
      - name: productsapi
        image: modoranuc/productsapi
        imagePullPolicy: Always
        env:
          - name: ConnectionStrings__Mongo__Host
            value: mongodb://host.minikube.internal:27017
          - name: EventQueue__Host
            value: host.minikube.internal
          - name: EventQueue__Username
            value: guest
          - name: EventQueue__Password
            value: guest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      
---
apiVersion: v1
kind: Service
metadata:
  name: productsservice
spec:
  selector:
    app: productsapi
  ports:
  - port: 8080
    targetPort: 80

